// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "server": {
    "en": "Server",
    "de": "Server",
    "ru": "Server",
    "pt": "Server",
    "nl": "Server",
    "fr": "Server",
    "it": "Server",
    "es": "Server"
  },
  "port_server": {
    "en": "Port",
    "de": "Port",
    "ru": "Port",
    "pt": "Port",
    "nl": "Port",
    "fr": "Port",
    "it": "Port",
    "es": "Port"
  }
};
